import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import "./globals.css"
import { UserProvider } from "@auth0/nextjs-auth0/client"

const font = Montserrat({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

const RootLayout = ({
	children,
}: {
	children: React.ReactNode
}) => {
	return (
		<html lang="en">
			<UserProvider>
				<body className={font.className}>{children}</body>
			</UserProvider>
		</html>
	)
}

export default RootLayout
